
export enum ARROW_KEYS {
    LEFT =  37,
    RIGHT = 39,
    JUMP = 38,
}

export enum DEFAULT_GAMEPLAY_ROLES {
  MAP_MARGIN_LEFT = -300,
  MAP_MARGIN_TOP = -300,
  MAP_MARGIN_RIGHT = 20000,
  MAP_MARGIN_BOTTOM = 4500,
  RESPAWN_INTERVAL = 1000,
}

export enum DEFAULT_RENDER_BOUNDS {
  WIDTH = 800,
  HEIGHT = 600,
}

export enum DEFAULT_NETWORK_PARAMS {
  SYNTETIC_ASYNC_DELAY_INTERVAL = 2000,
}

export enum DEFAULT_PLAYER_DATA {
  INITIAL_LIVES = 3,
  NEW_GAME_COST = 30,
  SPEED_AMP = 0.004,
}

